name: Feature request
description: Suggest an improvement
title: "[feature] "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: input
    id: version
    attributes:
      label: Conduit version
  - type: dropdown
    id: affects
    attributes:
      label: Would affect
      options: [server, UI, both, docs]
